summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/fpliu1214/uppm-package-repository-android-aarch64/releases/download/2025.01.21/fontconfig-2.15.0-android-aarch64.release.tar.xz
bin-sha: 7d2f569f2f5dd2b851b5a0b4a6d9dbc744313d2fa71cad77e5edfc458adfba0c
