summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-android-aarch64/releases/download/2024.04.28/pkg-config-0.29.2-android-aarch64.tar.xz
bin-sha: ec8db24d9d283d2570a9c387662d3d5d7df9d860afa13f340404fa91f2c17f08
