summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/fpliu1214/uppm-package-repository-android-aarch64/releases/download/2024.09.11/pkg-config-0.29.2-android-aarch64.tar.xz
bin-sha: dce4081575ffefbe629f70e44dcc781b6c90b39aaa88a01fff14276212280a29
