summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/fpliu1214/uppm-package-repository-android-aarch64/releases/download/2024.04.28/pkg-config-0.29.2-android-aarch64.tar.xz
bin-sha: eb8a3833a6ae6ce679ac7c5161efe4b0ae8995337e19a2e1fba9141f51aa4621
