name: publish

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pkg: [aria2, axel, base16, base64, bash, bat, bison, bc, bsdtar, bzip2, b3sum, cargo-c, cmake, coreutils, ctop, curl, curlie, darkhttpd, dua, duf, dufs, dust, diffutils, dog, dos2unix, easyutils, ed, exa, fd, figlet, file, findutils, flex, fzf, gawk, gettext-tools, gh, gindent, git, glib-tools, glow, gm4, gmake, gn, gnupg, go-md2man, gogs, golang, gotop, gotty, gperf, grep, grpc-plugins, gsed, gtar, gzip, hugo, jj, jq, lazygit, libxml2-utils, lolcat, lsd, lz4, lzip, mediainfo, mosh, mpg123, nasm, ninja, nushell, openssl, patch, patchelf, pigz, p7zip, pkg-config, pkgconf, pngquant, proot, putty, qpdf, qrencode, re2c, ripgrep, rsync, rtmpdump, sqlite3, starship, strace, svn-lite, swig, sysinfo, tcpdump, tealdeer, tig, tmux, tree, uctags, unrar, unzip, uppm, util-linux, volta, wget, xmake, xsltproc, xxd, xz, yasm, youtubedr, yq, zip, zopfli, zstd, zoxide]

    runs-on: ubuntu-latest

    #container: fpliu/ndk-pkg

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg
      - run: chmod a+x ndk-pkg
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg update

      - name: check package type
        run: |
          PKGTYPE="$(./ndk-pkg info-available gh pkgtype)"

          if [ -z "$PKGTYPE" ] ; then
            BSYSTEM="$(./ndk-pkg info-available gh bsystem)"
            
            if [ "$BSYSTEM" = go ] ; then
              echo "go package can not be installed as fully statically linked executables"
              exit 1
            fi
          else
            if [ "$PKGTYPE" != exe ] ; then
              echo "package type is not exe"
              exit 1
            fi
          fi

      - run: ./ndk-pkg install android-34-arm64-v8a/${{ matrix.pkg }} --exe=fsle
      - run: ./ndk-pkg pack    android-34-arm64-v8a/${{ matrix.pkg }} -o .

      - run: |
          PACKAGE_SUMMARY="\$(./ndk-pkg info-installed android-34-arm64-v8a/${{ matrix.pkg }} summary)"
          PACKAGE_WEB_URL="\$(./ndk-pkg info-installed android-34-arm64-v8a/${{ matrix.pkg }} web-url)"
          PACKAGE_VERSION="\$(./ndk-pkg info-installed android-34-arm64-v8a/${{ matrix.pkg }} version)"

          PACKAGE_BIN_SHA="\$(sha256sum *.tar.xz | cut -d ' ' -f1)"

          PACKAGE_BIN_URL="https://github.com/leleliu008/uppm-package-repository-android-aarch64/releases/download/@TAGNAME@/\$(ls *.tar.xz)"

          cat > ${{ matrix.pkg }}.yml <<EOF
          summary: \$PACKAGE_SUMMARY
          webpage: \$PACKAGE_WEB_URL
          version: \$PACKAGE_VERSION
          bin-url: \$PACKAGE_BIN_URL
          bin-sha: \$PACKAGE_BIN_SHA
          EOF

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ${{ matrix.pkg }}-*.tar.xz
            ${{ matrix.pkg }}.yml

  publish:
    needs: build
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls

      - run: |
          set -ex

          TAGNAME="$(date +%Y.%m.%d)"

          sed -i "s|@TAGNAME@|$TAGNAME|" *.yml

          mv *.yml formula/

          DIRNAME="uppm-formula-repository-android-aarch64-$TAGNAME"

          install -d "$DIRNAME"

          cp -r formula "$DIRNAME/"

          tar cvJf "$DIRNAME.tar.xz" "$DIRNAME"

          sha256sum *.tar.xz > sha256sums.txt

          cat > notes.md <<EOF
          these packages are created by [ndk-pkg](https://github.com/leleliu008/ndk-pkg).

          these packages are statically linked.

          these packages are relocatable which means that you can install them to anywhere.

          ## Environment Variables

          **following environment variables should be set for \`git\` package**

          \`\`\`bash
          export GIT_EXEC_PATH="\$GIT_INSTALL_DIR/libexec/git-core"
          export GIT_TEMPLATE_DIR="\$GIT_INSTALL_DIR/share/git-core/templates"
          \`\`\`

          **following environment variables should be set for \`file\` package**

          \`\`\`bash
          export MAGIC="\$FILE_INSTALL_DIR/share/misc/magic.mgc"
          \`\`\`

          ## sha256sum

          \`\`\`
          $(cat sha256sums.txt)
          \`\`\`
          EOF

          gh release create "$TAGNAME" *.tar.xz sha256sums.txt --title "$TAGNAME" --notes-file notes.md

          git config --global user.name  "leleliu008"
          git config --global user.email "leleliu008@gmail.com"

          git pull

          git add formula
          git commit -m "release new version $TAGNAME"
          git push origin master
